export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const RECEIVE_WISHLIST_DATA = 'RECEIVE_WISHLIST_DATA';
export const ADD_ITEM_FROM_WISHLIST = 'ADD_ITEM_FROM_WISHLIST';
export const ADD_ITEM_TO_WISHLIST = 'ADD_ITEM_TO_WISHLIST';
export const SHOW_WISHLIST = 'SHOW_WISHLIST';
export const HIDE_WISHLIST = 'HIDE_WISHLIST';

export const REQUEST_DATA = 'REQUEST_DATA';
